"""removendo restrict do ordemdistribuida

Revision ID: 7a1d7403fa9f
Revises: 76df79401028
Create Date: 2022-01-28 15:49:29.858659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1d7403fa9f'
down_revision = '76df79401028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ordemdistribuida_ibfk_2', 'ordemdistribuida', type_='foreignkey')
    op.drop_constraint('ordemdistribuida_ibfk_1', 'ordemdistribuida', type_='foreignkey')
    op.create_foreign_key(None, 'ordemdistribuida', 'employee', ['id_poster'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ordemdistribuida', 'employee', ['id_employee'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ordemdistribuida', type_='foreignkey')
    op.drop_constraint(None, 'ordemdistribuida', type_='foreignkey')
    op.create_foreign_key('ordemdistribuida_ibfk_1', 'ordemdistribuida', 'employee', ['id_employee'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('ordemdistribuida_ibfk_2', 'ordemdistribuida', 'employee', ['id_poster'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
